export let assortment = {
  "supplier": [
      { 
         "id":"12ffgd",
         "data":{ 
            "products":{ 
               "item1":{ 
                  "id":"c3e470",
                  "name":"appleTv"
               },
               "item2":{ 
                  "id":"14fcbd",
                  "name":"chicken"
               },
               "item3":{ 
                  "id":"123abc",
                  "name":"orange"
               },
            }
         },
         "id2":"12bbb",
         "data2":{ 
            "products2":{ 
               "item1":{ 
                  "id":"c3e400",
                  "name":"Ipad"
               },
               "item2":{ 
                  "id":"15fcbd",
                  "name":"fish"
               },
               "item3":{ 
                  "id":"5500ff",
                  "name":"apple"
               },
            }
         }
      }
  ]
}